### ISSUE TITLE
Delete Attachments

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#13]
At the moment deleting Attachments via API is not supported out of the box. There is a patch to solve the issue, but the patched redmine returns an error after deleting the attachment. If there is a better solution the Delete should be implemented later.

Patch:
https://www.redmine.org/issues/14828

**Comment by oliverluethi** [comment]
@rufer7 @dfch I've added a patch for this issue to redmine.org. I can't contribute with a pullrequest, because pullrequests are not allowed. The only way to contribute to redmine is to open an issue and attach a patch (git file) with the changes.

the question is, should i fork the redmine project or should i save all patches with all changes until the patches are merged into an official redmine release?

**Comment by rufer7** [comment]
@oliverluethi at what date the next major release is planned? If this functionality is not really necessary at the moment I would wait for the release.

**Comment by rufer7** [comment]
@dfch can you please give some feedback here?

**Comment by oliverluethi** [comment]
@rufer7 There's no date at all at the moment. There's only a [roadmap ](http://www.redmine.org/projects/redmine/roadmap).

**Comment by rufer7** [comment]
According [roadmap](http://www.redmine.org/projects/redmine/roadmap) this will be fixed with release `3.3.0`
